# Test, build, and deploy a svelte app to GitHub Pages in a GitHub Actions workflow
name: CICD

on:
  push:
    branches:
      - main

jobs:
    deploy:
        runs-on: ubuntu-latest
    
        steps:
        - uses: actions/checkout@v4
    
        - name: Use Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '20'
    
        - name: Install dependencies
          working-directory: ./turbocharge-todo
          run: npm install

        - name: Test
          working-directory: ./turbocharge-todo
          run: npm run test

        - name: Build
          working-directory: ./turbocharge-todo
          run: npm run build
    
        - name: Deploy
          uses: actions/upload-pages-artifact@v3
          with:
            path: build 